### ISSUE TITLE
[2024.02] README에 방향성 정리 & 2월 계획 설정 및 실행

### ISSUE THREAD

**Issue by fsm12** [fsm12/Dev-Book#1]
## ✅ To-Do-List

- [x] `README.md` 기본 틀 작성
- [ ] 기존 정리본 업로드 -> 리드미에 링크로 연결
- [ ] 2월에 공부할 레퍼런스 선택
- [x] 각 과목에 따른 공부 계획 `Story 디렉토리`에 기록
- [ ] 최소 주 1회 공부한 내용 `push`
- [ ] 마지막날 회고
